apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sample-api
  namespace: demo-app
  labels:
    app: sample-api
spec:
  selector:
    matchLabels:
      app: sample-api
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 30s
