apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: demo-app
  annotations:
    azure.workload.identity/client-id: "f8199a1f-4baa-49f8-8d29-c08ee4e50e6a"
  labels:
    azure.workload.identity/use: "true"
    app: sample-api
    environment: dev
    owner: platform-team
